# Introduction To Matrices_In Python Using Numpy

In [1]:
import numpy as np
import random 

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Two by two matrix

In [15]:
T = np.random.randint(-2,4,size=(2,2))
T

array([[ 0,  3],
       [ 0, -1]])

## Particular Matrices

* Identity Matix

In [21]:
I = np.eye(3,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

* Zeros Matrix

In [13]:
Z = np.zeros((3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* Ones matrix

In [17]:
O = np.ones((4,3))
O

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* Diagonal matrix

In [18]:
D = np.diag([1,2,3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
C = np.diag(M)
C

array([1, 5, 9])