In [1]:
import numpy as np
import sympy as sy
import random

In [2]:
L = np.linspace(0,120,25)

In [16]:
M = L.reshape(5,5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [6]:
# Using Random Integers

In [13]:
R = np.random.randint(-4,6,size=(5,5))
R

array([[-2,  0,  4,  0,  3],
       [ 4,  5,  5,  1, -1],
       [-2,  0,  0, -3, -2],
       [ 4,  5,  0, -4, -2],
       [ 3,  3,  0,  1,  3]])

In [14]:
# Populate a Matrix Manually

In [18]:
A = np.array([[1,2,3],[-5,9,11]])
A

array([[ 1,  2,  3],
       [-5,  9, 11]])

In [19]:
C= np.array([[5],[-7],[3]])
C

array([[ 5],
       [-7],
       [ 3]])

In [21]:
RW = np.array([6,8,4])
RW

array([6, 8, 4])

In [23]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [30]:
M[0]

array([ 0.,  5., 10., 15., 20.])

In [25]:
M[0,0:5]

array([ 0.,  5., 10., 15., 20.])

In [26]:
M[0,:]

array([ 0.,  5., 10., 15., 20.])

In [27]:
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [28]:
M[:,2]

array([ 10.,  35.,  60.,  85., 110.])

In [31]:
M[2:3,3:4]

array([[65.]])

In [32]:
M[0:3,2:4]

array([[10., 15.],
       [35., 40.],
       [60., 65.]])