In [1]:
import numpy as np
import random

In [2]:
# Matrix Multiplcation

In [3]:
M = np.linspace(-8,8,9).reshape(3,3)
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [4]:
N = np.random.randint(-8,8,size=(3,3))
N

array([[-1,  6,  4],
       [ 0,  4,  5],
       [-2, -7,  3]])

In [5]:
N.dot(M)

array([[12., 30., 48.],
       [12., 30., 48.],
       [42., 30., 18.]])

In [6]:
np.matmul(N,M)

array([[12., 30., 48.],
       [12., 30., 48.],
       [42., 30., 18.]])

In [7]:
N@M

array([[12., 30., 48.],
       [12., 30., 48.],
       [42., 30., 18.]])

In [8]:
# Deteminant of a matrix

In [9]:
np.linalg.det(M)

0.0

In [23]:
val,vect = np.linalg.eigh(M)

In [24]:
val

array([-10.21449908,  -1.35402017,  11.56851926])

In [25]:
vect

array([[-0.88172518, -0.45143624,  0.13698914],
       [-0.35508874,  0.8262437 ,  0.43730234],
       [ 0.31060053, -0.33693719,  0.8888198 ]])

In [10]:
np.linalg.det(N)

-75.00000000000004

In [11]:
# More Operations

* Addition

In [12]:
M+N

array([[-9.,  0.,  0.],
       [-2.,  4.,  7.],
       [ 2., -1., 11.]])

In [13]:
N+M

array([[-9.,  0.,  0.],
       [-2.,  4.,  7.],
       [ 2., -1., 11.]])

In [14]:
 A = np.array([[2,4,6],[8,10,12]])
A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
B = np.array([[1,3,5],[7,9,11]])
B

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [16]:
B.dot(A.T)

array([[ 44,  98],
       [116, 278]])

In [17]:
A.T

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [18]:
2x3 3x2

SyntaxError: invalid syntax (Temp/ipykernel_25596/4141345363.py, line 1)